name: Build and deploy .NET Core application to Web App API20250228131943
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: API20250228131943
  AZURE_WEBAPP_PACKAGE_PATH: API/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: API
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Restore
      run: dotnet restore API
    - name: Build
      run: dotnet build API --configuration Release --no-restore
    # - name: Test
    #   run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish API --configuration Release --no-build --output API/publish
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: API/publish
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: API/publish
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: API20250228131943
        publish-profile: ${{ secrets.API20250228131943_E5DB }}
        package: API/publish
